// Code generated by "stringer -type=ValueKind"; DO NOT EDIT.

package values

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValueKindString-0]
	_ = x[ValueKindInteger-1]
	_ = x[ValueKindList-2]
}

const _ValueKind_name = "ValueKindStringValueKindIntegerValueKindList"

var _ValueKind_index = [...]uint8{0, 15, 31, 44}

func (i ValueKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ValueKind_index)-1 {
		return "ValueKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueKind_name[_ValueKind_index[idx]:_ValueKind_index[idx+1]]
}
